module.exports = {
    jobs : [
        {name: "become farmer", icon: "👨‍🌾"},
        {name: "go to fishing", icon: "🎣"},
        {name: "Miner and craft", icon: "⛏️"},
        {name: "let me cook", icon: "👨‍🍳"},
        {name: "Teach dumb kids", icon: "👩‍🏫"},
        {name: "Cure someone", icon: "👨‍⚕️"},
        {name: "Engineer", icon: "👷‍♂️"},
        {name: "Draw something", icon: "🎨"},
        {name: "create a song", icon: "🎵"},
        {name: "Write a random book", icon: "✍️"},
        {name: "coding a discord bot", icon: "💻"}
    ],
    jobs_txt: [
        'Keep up the good work!',
        'Don\'t forget to take breaks and stay hydrated!',
        'Every job is important, no matter how small it may seem.',
        'Your hard work will pay off in the end!',
        'Remember to always do your best and never give up!',
    ],

    NPC: [
        'Elon Muska (broke version)',
        'Rich Kid who flexes with his dad’s black card',
        'Older Woman in a Luxury Car (she’s judging you)',
        'Owner of the Discord Server',
        'Kimori\'s Kaechan',
        'Your Mom (disappointed)',
        'Your Dad (about to give life advice)',
        'Your Ex who owes you money',
        'Grandma with gambling addiction',
        'meh23_.',
        'Ghost living under your bed',
        'Santaa Claus (he saw your search history)',
        'Yourself from 3 years ago',
        'Your Ancestor who’s ashamed of you',
        'Your Dog (he has more money than you)',
        'Triple T',
        'Skeleton in the closet',
        'Your House (it’s also broke)',
        'Mr. Aintsir',
        'The Archive in Blue\'s Student',
        'UwU Supreme Overlord',
        'Damn Meme',
        'Lyno',
        'Something Sent From Heaven (but broke)',
        'Literally No One Cares But Money Suddenly Drops',
        'Must Be Wind',
        'Holy Cow',
        'Religious Sect That Doesn’t Believe Earth Exists',
        'Alien Here For Your Data',
        'Emperor of Humanity (mid af)',
        'Chat aint GPT',
        'Super AI from 2035 (still unemployed)',
        'Dinosaurus',
        'Niissan',
        'Brazil Guy',
        'Hacker (uses Windows 7)',
        'Corrupt Politician',
        'Scammer from WhatsApp',
        'Street Musician (plays only Wonderwall)',
        'Lost Tourist',
    ],

    // Beg command
    // Beg command - MAXIMUM SOUL
    BegSuccess: [
        'You begged in the toilet and suddenly MrBeast liked your comment',
        'No one came but then a crypto whale randomly dropped 0.5 ETH on you',
        'You went to the bank looking homeless and they just gave you money out of pity',
        'Got hit while begging but a sugar mommy appeared saying "aww poor baby"',
        'Sat outside Gucci looking dead inside and someone Venmo’d you $420',
        'Went live begging and xQC raided you with 500 gifted subs',
        'Broke af so you hit up school and Kimori\'s Kaechan felt bad',
        'You asked your mom and she actually opened her wallet (rare event)',
        'Found a lost iPhone wallet case with Apple Pay still logged in',
        'A mysterious stranger said "you remind me of me in 2009" and gave you $1000',
    ],
    SelfBeg: [
        'You tried begging yourself and somehow the universe still felt bad for you',
        'Self-begging got you a pity check from your own emotional damage',
        'You begged yourself so hard even your inner voice said "bro, enough"',
        'Your self-esteem got mugged while you begged yourself for spare change',
        'Even your reflection looked disappointed after that self-beg attempt',
    ],
    BegFail: [
        'Police arrested you for begging in the women’s toilet again',
        'Your mom wasn’t home (classic)',
        'Livestream begging got 2 views and 1 hate comment',
        'Dad slapped you with the "get a job" speech',
        'Gym bro only gave you "touch grass and lift" advice',
        'Stood in rain for 2 hours and got nothing but pneumonia + L',
        'Your ancestor appeared and said "skill issue" before vanishing',
        'Brazil guy said "ye" and kept walking',
        'Luxury car lady saw you and floored it',
        'You tried to text your gf then remembered you’re single',
        'Join beggar company lil bro',
        'Imagine being this poor lol 😂😂😂',
        'I TOLD U NO',
        'I CANT STOP I CANT STOP I CANT STOP',
        'Ratio + touch grass + L + no maidens',
    ],
    BegStolen: [
        'Random old woman on bike snatched your bag like a pro',
        'Beggar company guy stole everything while screaming "I CANT STOP"',
        'Bike kid did a drive-by theft',
        'You tripped and a kid kicked your money into the drain',
        'Monkey from the market stole your wallet mid-beg',
        'Officer you begged arrested you for "suspicious behavior"',
        'School bully suplexed you and took everything',
        'Your situationship appeared and said "babe send money"',
        'Lost the 1v1 against hydrogen bomb vs coughing baby',
        'Kimori\'s Kaechan walked past like you were invisible',
        'Tried robbing a skeleton… he had no pockets',
        'Brazil guy casually yoinked half your money',
        'Discord owner used /admin deletebalance on you',
    ],

    // Steal command
    StealSuccess: [
        'You pulled the smoothest wallet heist since Ocean’s Eleven',
        'They were watching Skibidi Toilet. You watched their wallet vanish',
        '"LOOK A SHOOTING STAR" — wallet + phone gone',
        'Swapped their wallet with a fake one. They still haven’t noticed',
        'Food court sleight of hand = new PS5 fund',
        'Hugged them goodbye and left with their entire salary',
        'Pointed at something shiny and executed perfect pickpocket',
    ],
    StealFail: [
        'Wrong pocket. They gave you the "bro what are you doing" stare',
        'Your hand shook. You just did the default dance and left',
        'They turned around mid-grab. You said "Zsteal is mid" and walked away',
        'Fumbled and gave them a high five instead. Legendary fail',
        'They had AirPods but 360 awareness. Caught you instantly',
        'Your "casual" walk looked like you were constipated. Super sus',
        'Knocked over an entire shelf. Main character energy (negative)',
    ],
    StealBusted: [
        'Caught red-handed. Whole server spamming L + ratio',
        'Tripped while running and spilled your own wallet. Pain',
        'They had a bodycam. You’re now a Discord meme',
        'Off-duty cop was standing right there. Instant jail arc',
        'Lost money + dignity in one go. Tragic.',
        'They grabbed your wrist and said "nice try kid"',
        'They reverse pickpocketed YOU. Ultimate ratio',
    ],

    // Crime command (Rob)
    CrimeSuccess: [
        'You robbed a bank like it was GTA and actually escaped',
        'Old lady dropped wallet. You pulled a Sonic speedrun.',
        'Snuck into tech store and walked out with 3 gaming PCs',
        'Hacked emptyY database and sold it to the highest bidder',
        'Pickpocketed a rich tourist and found $5000 cash',
        'Hotwired a Lamborghini and sold it in under 20 minutes',
        'Perfect mall heist. Security guards were asleep.',
        'Phishing scam worked. Some boomer sent you his retirement fund.',
    ],
    CrimeFail: [
        'Bank teller laughed at your toy gun. You ran away crying',
        'Old lady folded you like a cheap chair. Hospital bill + L',
        'PC too heavy. Dropped it, broke the glass, ran empty handed',
        'Forgot VPN. Cyber police traced you in 4 seconds.',
        'Pickpocketed an undercover cop. Handcuffs speedrun any%.',
        'Car alarm went nuclear. Whole city woke up',
        'Scam victim reversed it and drained your account.',
    ],
    CrimeWorse: [
        'SWAT team appeared. You’re now someone’s prison wife',
        'Old lady was ex-MMA. You woke up with $50k medical bill',
        'Store owner had shotgun. You got shot + arrested + sued',
        'FBI raided your house at 3AM. Setup = gone',
        'Undercover cop moment. Welcome to jail',
        'Crashed stolen car into police station. Record charges',
        'Victim doxxed you and leaked your browser history',
    ],

    // Job command
    JobStart: [
        'Alarm goes off. You drag your dead soul to the wage cage',
        'Coffee + existential dread = another corporate day',
        'Showed up 15 minutes late with boba like you own the company',
        'Boss said "start working" and your 2 brain cells panicked',
        'Another day of pretending to look busy',
    ],
    JobSuccess: [
        'Never gonna give you up… paycheck just hit different',
        'You actually cooked today. Boss almost smiled.',
        'Grind paid off. Pockets no longer sobbin.',
        'Went full gigachad mode and made it look easy',
        'Finished early. Coworkers gave slow clap + respect',
        'Boss said "good job" — you almost shed a tear',
    ],
    JobFail: [
        'Go work at scam company, you are NOT built for this',
        'Boss gave you the disappointed dad stare',
        'Complete disaster. Even your chair is judging you.',
        'Came late. Boss is now your final boss.',
        'Client asked for your manager. Manager cried',
        'You tried your best… your best was tragic.',
        'Task so hard even Superman said "nah"',
    ],

    // Minigames
    HelperNPC_intro: [
        'Random NPC appears: "Hey bro… can you help me or I’ll haunt your wallet?"',
        'Tiny NPC tugs your shirt: "Psst. I need a favor... or I bite your kneecaps"',
        'Suspicious NPC waves: "Help me before this gets weird... too late, it’s already weird"',
        'Your gf’s dad appears: "Help me or no dating my daughter and I’ll show her your search history"',
        'Famous footballer NPC: "Help me win the championship or I’ll miss the penalty on purpose!"',
        'Ghost in haunted mansion: "Help or be cursed forever, starting with your Spotify Wrapped"',
        'Alien NPC: "Fix my spaceship or we both stranded and I’ll probe your search history"',
        'Karen NPC materializes: "I need to speak to the manager of reality about this quest"',
        'Depressed NPC: "Bro my life is a side quest and it’s bugged"',
        'Cat NPC appears: "Meow. Help me or I knock your entire inventory off the table"',
        'Crypto bro NPC: "Help me pump this coin or it’s permanently rugged, fr fr no cap"',
        'Your mom NPC: "Son, help me before I tell everyone what you did at 3:17 AM last Tuesday"',
        'Time traveler NPC: "Help me fix the timeline or your future self will keep sending you sad memes"',
        'Boss NPC: "Do this quest or you’re fired... from existence"',
        'Shy NPC: "Umm… can you help? I’ll give you my only rare Pepe"',
        'Pirate NPC: "Help me find me treasure or I’ll make ye walk the plank... into the friendzone"',
        'Edgy NPC: "Help me or I’ll write a 12-page Tumblr essay about how mid you are"',
    ],

    HelperNPC_help_success: [
        'NPC cried happy tears and gave you a fat reward (it was 3 gold and emotional damage)',
        'You helped and they blessed your bloodline with +1000 aura',
        '"You\'re the best!" — NPC skipped away happily while vibrating with joy',
        'NPC hugged you so hard your HP went to 999',
        'They Venmo’d you their life savings... in Robux',
        'NPC reveals they were a god in disguise and grants you "Main Character Energy" passive',
        'You fixed their problem. They now call you "The Legend" unironically.',
        'NPC throws a parade in your honor. You get confetti in your inventory forever.',
        'They baked you cookies that give permanent +50 rizz',
        'NPC does the sigma handshake and unlocks the secret "Based" achievement',
        'You helped so well the NPC became your loyal companion who carries all your junk',
        '"Bro you actually saved me" — NPC gives you their rarest skin',
    ],

    HelperNPC_watch_success: [
        'You watched like a true sigma. Situation fixed itself out of fear',
        'Sometimes doing nothing is the best move. NPC respected your aura',
        'You sigma stared so hard the problem deleted itself.',
        'Zero effort, maximum respect. NPC now calls you "The Watcher"',
        'You stood there menacingly. The quest resolved itself to avoid confrontation.',
        'True chad move: You touched grass while the NPC figured it out',
        'You vibed so hard the universe gave you +500 rizz for free',
        'You did absolutely nothing and still got the good ending. Skill issue avoided',
    ],

    HelperNPC_run_fail: [
        'You ran. NPC was faster and 10x angrier.',
        'Running made it worse. Karma caught you instantly and slapped you.',
        'NPC teleports in front of you: "Nice try, speedrunner."',
        'You tripped over nothing. NPC laughed and cursed your entire bloodline.',
        'You ran so fast you entered a new dimension... still haunted by the NPC.',
        'Escape failed. NPC now has your IP and sends you daily disappointment memes.',
        'You yeeted yourself into failure. NPC sends you a therapy bill.',
        'Running made the NPC go full final boss mode.',
    ],

    HelperNPC_fail: [
        'NPC stared at you, sighed, and left disappointed',
        'You were so mid the NPC forgot you existed mid-conversation',
        'NPC: "Nevermind, I’ll ask someone with aura."',
        'Your help attempt backfired so hard the NPC started roasting you publicly',
        'Epic fail. NPC gives you the disappointed dad look x1000',
        'You tried... and manifested -500 aura points',
        'NPC ghosted you harder than your situationship ever could',
        '"Thanks for nothing, beta." — NPC walks away in cinematic slow motion',
        'Failure so bad it lowered the server’s average IQ by 20 points',
        'NPC: "Wow. Even my side character friends are more useful than you."',
        'You failed so spectacularly the game offered you a participation trophy',
    ],

    GuessNum_intro: [
        'Final boss challenges you to guess a number 1-10 to save the princess... or he’ll simp for her instead',
        'Beggar company boss: "Guess right or stay broke forever, broke boy"',
        'Coin Walls, CEO of Bighard, challenges you for the jackpot: "Wrong guess = stay mid"',
        'Death himself: "Guess right or stay dead... and I’ll make your afterlife mid too"',
        'Your gf’s dad: "Guess right or no daughter... and I’ll show her your search history"',
        'Crypto bro NPC: "Guess the number or this coin stays rugged"',
        'Karen NPC: "Guess correctly or I’m speaking to the manager of your bloodline"',
        'Your mom: "Guess right or I’m telling everyone what you did at 2AM last night"',
        'Time traveler: "Guess the number or your future self remains unemployed"',
        'Alien invader: "Guess right or Earth gets destroyed... starting with your WiFi"',
    ],

    GuessNum_won: [
        'BULLSEYE. You’re actually him. The main character.',
        'You read the universe’s mind. Bag secured. Rizz levels: ∞',
        'Destiny chose you today. Even the devs are impressed.',
        'You cooked so hard the number itself started clapping',
        'Sigma guess. The universe just got ratio’d',
        'You guessed it perfectly. NPC starts calling you "The Oracle"',
        'Bingo. Your aura just broke the server',
        'Correct. The princess is now down bad for you',
    ],

    GuessNum_lost: [
        'So close yet so broke',
        'Universe said "skill issue"',
        'The number laughed at you and left on a yacht',
        'You got ratio’d by a random integer',
        'Tragic. Even a monkey on ketamine would’ve guessed better',
        'Wrong. Your ancestors are currently disappointed',
        'You fumbled the bag harder than your situationship',
        'The game devs are laughing at you in the group chat',
        'Mid guess. NPC now feels bad for you... that’s worse',
    ],

    PenaltyKick_goal: [
        'TOP BINS!!! Keeper had no chance',
        'GOAAAAL!!! Crowd goes feral',
        'The ball had no choice but to go in',
        'Pooland mode activated — absolute rocket',
        'Ninja Turtle speed + Ronaldo power = Keeper in therapy',
        'You channeled Prime Simét and chipped him like a Sunday league keeper',
        'Seleh curled it so beautifully the keeper started crying',
        'You did the Maraintney rainbow flick then smashed it top corner',
        'Kane with the ice-cold penalty — keeper never had a chance',
        'You went full Van Persie — flying header from a penalty somehow',
        'Ball hit the post so hard it apologized and went in',
    ],

    PenaltyKick_saved: [
        'Keeper read your mind like a book',
        'Spectacular save. You got ratio’d by the keeper',
        'Newer just pulled a miracle save. You got psychologically damaged',
        'Alice Son turned into a wall. Your shot got embarrassed',
        'Buff and on in his prime just woke up and saved that',
        'The keeper did the spider-man save. You got violated',
        'He saved it with his face... and still looked cooler than you',
        'Keeper started dancing after the save. Your aura went negative',
        'A 40 year old keeper saved it like he was 20. You got roasted and you realized he actually from a country half of million people that you nerver heard of',
    ],

    // Leaderboard
    LeaderboardConfig: {
        DefaultCategory: 'money',
        PageSize: 5,
        Color: {
            Gold: '#ffd700',
            DeepGreen: '#215004',
            BloodRed: '#931313',
            DirtyGold: '#93900e',
            DeepBlue: '#403d98',
            DeepPurple: '#3e0e5e',
            Magenta: '#ea5299',
            Orange: '#e67729',
            MustardYellow: '#e6d129',
            Cyan: '#0ea096',
            SkyBlue: '#53a0ea',
        },
        Emoji: {
            '1': '🥇',
            '2': '🥈',
            '3': '🥉',
            '4': '🔹',
            '5': '🔹',
            '6': '🔹',
            '7': '🔹',
            '8': '🔸',
            '9': '🔸',
            '10': '🔸',
        }
    }
}